//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lugar
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Usuario { get; set; }
        public string Categoria { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> Asistentes { get; set; }
        public string Descripcion { get; set; }
    }
}
